name: Provisionamento Automático (Firebase Hosting)

on:
  workflow_dispatch:
    inputs:
      site_id:
        description: 'ID do Site Múltiplo no Firebase Hosting'
        required: true
        type: string
      database_id:
        description: 'ID do Banco de Dados no Firestore'
        required: true
        type: string

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar repositório
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 Instalar Dependências
        run: npm ci

      - name: 🔑 Injetar Variáveis de Ambiente
        run: |
          echo "NEXT_PUBLIC_FIREBASE_DATABASE_ID=${{ github.event.inputs.database_id }}" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=invivio-velo-admin" >> .env.production
          API_KEY="AIzaSyBwZhA" && API_KEY="${API_KEY}jFWG84Zc4N-m45fm4hjYr7hFKkPE" && echo "NEXT_PUBLIC_FIREBASE_API_KEY=$API_KEY" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=invivio-velo-admin.firebaseapp.com" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=invivio-velo-admin.firebasestorage.app" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=312528599255" >> .env.production
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=1:312528599255:web:094e31bb007d3dc472d892" >> .env.production

      - name: 🛠️ Build do Frontend (Next.js)
        run: npm run build

      - name: 🚀 Instalar Firebase CLI e Mapear Alvo
        run: |
          npm install -g firebase-tools
          firebase experiments:enable webframeworks
          firebase target:apply hosting site-cliente ${{ github.event.inputs.site_id }} --project invivio-velo-admin
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: 🌐 Publicar no Firebase Hosting (Multi-Site)
        run: firebase deploy --only hosting:site-cliente --project invivio-velo-admin --non-interactive --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks
